const buildPlaceholderImage = (
  width: number,
  height: number,
  text: string,
  background = "E5E7EB",
  foreground = "6B7280",
) => ({
  uri: `https://placehold.co/${width}x${height}/${background}/${foreground}.png?text=${encodeURIComponent(
    text,
  )}`,
});

export const remotePlaceholders = {
  appLogo: buildPlaceholderImage(450, 228, "Logo", "13276F", "FFFFFF"),
  arrowLeft: buildPlaceholderImage(48, 48, "Back"),
  socialApple: buildPlaceholderImage(40, 40, "Apple", "111827", "FFFFFF"),
  socialGoogle: buildPlaceholderImage(40, 40, "Google", "FFFFFF", "DC2626"),
  notification: buildPlaceholderImage(40, 40, "Bell"),
  search: buildPlaceholderImage(48, 48, "Search"),
  filter: buildPlaceholderImage(48, 48, "Filter"),
  check: buildPlaceholderImage(48, 48, "Tick", "DCFCE7", "166534"),
  settingsEdit: buildPlaceholderImage(48, 48, "Edit"),
  chevronRight: buildPlaceholderImage(32, 32, ">"),
  fabViewMeal: buildPlaceholderImage(64, 64, "View"),
  fabLogMeal: buildPlaceholderImage(64, 64, "Log"),
  backgroundOne: buildPlaceholderImage(1200, 2400, "Background+1", "FFF7ED", "9A3412"),
  backgroundTwo: buildPlaceholderImage(1200, 2400, "Background+2", "EFF6FF", "1D4ED8"),
  getStartedHero: buildPlaceholderImage(900, 900, "Hero", "FEF3C7", "92400E"),
  getStartedAltHero: buildPlaceholderImage(900, 900, "Hero+2", "E0F2FE", "075985"),
  logoBlue: buildPlaceholderImage(320, 120, "Logo", "DBEAFE", "1D4ED8"),
  logoWhite: buildPlaceholderImage(320, 120, "Logo", "0F172A", "FFFFFF"),
  tabHome: buildPlaceholderImage(48, 48, "Home"),
  tabProgress: buildPlaceholderImage(48, 48, "Prog"),
  tabMeals: buildPlaceholderImage(48, 48, "Meal"),
  tabResources: buildPlaceholderImage(48, 48, "Res"),
  tabMore: buildPlaceholderImage(48, 48, "More"),
  settingsNotifications: buildPlaceholderImage(40, 40, "Notif"),
  settingsChangePassword: buildPlaceholderImage(40, 40, "Pwd"),
  settingsContactUs: buildPlaceholderImage(40, 40, "Help"),
  settingsPrivacy: buildPlaceholderImage(40, 40, "Privacy"),
  settingsTerms: buildPlaceholderImage(40, 40, "Terms"),
  settingsManageSubscription: buildPlaceholderImage(40, 40, "Plan"),
  settingsFaq: buildPlaceholderImage(40, 40, "FAQ"),
  settingsLogout: buildPlaceholderImage(40, 40, "Out"),
} as const;
